//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ops")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ops", IsNullable=false)]
public partial class OPS_envelope {
    
    private header headerField;
    
    private body bodyField;
    
    /// <remarks/>
    public header header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public body body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ops")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ops", IsNullable=false)]
public partial class header {
    
    private string versionField;
    
    /// <remarks/>
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ops")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ops", IsNullable=false)]
public partial class body {
    
    private data_block data_blockField;
    
    /// <remarks/>
    public data_block data_block {
        get {
            return this.data_blockField;
        }
        set {
            this.data_blockField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ops")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ops", IsNullable=false)]
public partial class data_block {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dt_array", typeof(dt_array))]
    [System.Xml.Serialization.XmlElementAttribute("dt_assoc", typeof(dt_assoc))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalar", typeof(dt_scalar))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalarref", typeof(dt_scalarref))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ops")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ops", IsNullable=false)]
public partial class dt_array {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dt_array", typeof(dt_array))]
    [System.Xml.Serialization.XmlElementAttribute("dt_assoc", typeof(dt_assoc))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalar", typeof(dt_scalar))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalarref", typeof(dt_scalarref))]
    [System.Xml.Serialization.XmlElementAttribute("item", typeof(item))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ops")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ops", IsNullable=false)]
public partial class dt_assoc {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dt_array", typeof(dt_array))]
    [System.Xml.Serialization.XmlElementAttribute("dt_assoc", typeof(dt_assoc))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalar", typeof(dt_scalar))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalarref", typeof(dt_scalarref))]
    [System.Xml.Serialization.XmlElementAttribute("item", typeof(item))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ops")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ops", IsNullable=false)]
public partial class dt_scalar {
    
    private object[] itemsField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dt_array", typeof(dt_array))]
    [System.Xml.Serialization.XmlElementAttribute("dt_assoc", typeof(dt_assoc))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalar", typeof(dt_scalar))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalarref", typeof(dt_scalarref))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ops")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ops", IsNullable=false)]
public partial class dt_scalarref {
    
    private object[] itemsField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dt_array", typeof(dt_array))]
    [System.Xml.Serialization.XmlElementAttribute("dt_assoc", typeof(dt_assoc))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalar", typeof(dt_scalar))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalarref", typeof(dt_scalarref))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ops")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ops", IsNullable=false)]
public partial class item {
    
    private object[] itemsField;
    
    private string[] textField;
    
    private string keyField;
    
    private string classField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dt_array", typeof(dt_array))]
    [System.Xml.Serialization.XmlElementAttribute("dt_assoc", typeof(dt_assoc))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalar", typeof(dt_scalar))]
    [System.Xml.Serialization.XmlElementAttribute("dt_scalarref", typeof(dt_scalarref))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
}
